version: '3'

services:
  main:
    build:
      context: .
      args:
        TARGET: aarch64-apple-darwin
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    environment:
      TARGET: aarch64-apple-darwin

