name: Build Rust App

on:
  push:
    branches: [ main ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Add macOS target (Apple Silicon)
        run: rustup target add aarch64-apple-darwin

      - name: Build release binary
        run: API_TOKEN=${{ secrets.YOUTUBE_V3_API_TOKEN }} cargo build --release --target aarch64-apple-darwin

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-binary
          path: target/aarch64-apple-darwin/release/search-yt-pl
